# Generated by Django 3.2 on 2025-04-25 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Delemon_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='seo_title',
        ),
    ]
