# Generated by Django 3.2 on 2025-04-25 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delemon_App', '0002_auto_20250425_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='seo_Description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='seo_Title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
