from django.urls import path
from .import views



urlpatterns = [
    path('base', views.base, name='base'),
    path('', views.home, name='home'),
    path('robots', views.robots_txt, name="robots_txt"),
    path('homenew', views.homenew, name='homenew'),
    path('landingservice', views.landingservice, name='landingservice'),
    path('privacy-policy-digital-services', views.privacy, name='privacy'),
    path('terms-and-conditions-digital-marketing', views.terms, name='terms'),
    path('contact-digital-experts', views.contact, name='contact'),
    path('about-digital-technology', views.about, name='about'),
    path('digital-marketing-and-advertising-services', views.digital, name='digital'),
    path('web-development-and-design-solutions', views.web, name='web'),
    path('full-digital-services', views.services, name='services'),
    path('mobile-app-development-services', views.mobile, name='mobile'),    
    path('ios-app-development-services', views.iphone, name='ios'),
    path('android-app-development-services', views.android, name='android'),
    path('flutter-app-development-services', views.flutter, name='flutter'),    
    path('ecommerce-development-solutions', views.ecommerce, name='ecommerce'),
    path('woocommerce-development-solutions', views.woocommerce, name='woocommerce'),
    path('shopify-development-solutions', views.shopify, name='shopify'),
    path('magento-development-solutions', views.magento, name='magento'),
    path('wordpress-development-solutions', views.wordpress, name='wordpress'),
    path('customeweb-development-solutions', views.customeweb, name='customeweb'),
    path('python-development-solutions',views.python,name='python'),
    path('react-development-solutions',views.react,name='react'),
    path('java-development-solutions',views.java,name='java'),
    path('blockchain-development-solutions',views.blockchain,name='blockchain'),
    path('php-development-solutions',views.php,name='php'),
    path('angular-development-solutions',views.angular,name='angular'),
    path('softwaretesting-development-solutions',views.softwaretesting,name='softwaretesting'),
    path('nodejs-development-solutions',views.nodejs,name='nodejs'),
    path('dotnet-development-solutions',views.dotnet,name='dotnet'),
    path('ui-ux-design-for-better-experience', views.uiux, name='uiux'),
    path('advertising-for-better-experience', views.advertising, name='advertising'),    
    path('branding-for-better-experience', views.branding, name='branding'),
    path('animation-design-and-services', views.animation, name='animation'),
    path('email-marketing-services', views.email, name='email'),
    path('clinical', views.clinical, name='clinical'),
    path('research-marketing-services', views.research, name='research'),
    path('influencer-marketing-services',views.influencer,name='influencer'),    
    path('digital-design',views.digital_design,name='digital_design'),
    path('logo-design',views.logo_design,name='logo_design'),
    path('product-design',views.product_design,name='product_design'),
    path('print-design',views.print_design,name='print_design'),
    path('graphic-design',views.graphic_design,name='graphic'),    
    path('digital-project-portfolio', views.projects, name='projects'),
    path('luxury-acres-digital-project', views.luxuryacres, name='luxuryacres'),
    path('chrono-corp-innovative-solutions', views.chronocorp, name='chronocorp'),
    path('ppc-advertising-management-services', views.ppc, name='ppc'),
    path('pps-production-services', views.pps, name='pps'),
    path('seo-optimization-and-services', views.seo, name='seo'),
    path('sem-marketing-and-services', views.sem, name='sem'),
    path('digital-career-opportunities', views.careers, name='careers'),
    path('our-expert-digital-team', views.team, name='team'),
    path('who-we-are-digital-experts', views.whoweare, name='whoweare'),
    path('content-marketing-strategy-services', views.content, name='content'),
    path('social-media-marketing-strategies', views.social, name='social'),
    path('real-estate-digital-listings', views.realestate, name='realestate'),
    path('blog/', views.blog, name='blog'),
    path('blog/<slug:slug>/', views.blog_detail, name='blog_detail'),
    # path('teams', views.teams, name='teams'),
    path('news/', views.news_list, name='news_list'),
    path('news/<slug:slug>/', views.news_detail, name='news_detail'),
    path('sitemap.xml', views.sitemap, name='sitemap'),
   

]

